modLoader="javafml"
loaderVersion="[47,)"
license="GNU GPLv3"

[[mods]]
  modId="controllableintegration"
  version="0.1.1"
  displayName="Controllable Integrations"
  authors="NinjaPhase"
  description='''Controller Integrations with other mods.'''

[[dependencies.controllableintegration]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.controllableintegration]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.controllableintegration]]
    modId="controllable"
    mandatory=false
    versionRange="[0.20.3,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.controllableintegration]]
    modId="refinedstorage"
    mandatory=false
    versionRange="[1.12.4,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.controllableintegration]]
    modId="cobblemon"
    mandatory=false
    versionRange="[1.5.2,)"
    ordering="NONE"
    side="CLIENT"
